CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS recipe (
    difficulty SMALLINT CHECK (difficulty BETWEEN 0 AND 3),
    is_active BOOLEAN,
    prep_time FLOAT,
    servings INTEGER,
    creation_date TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    photo_url VARCHAR(500),
    description VARCHAR(1000)
);